###

post http://localhost:7001/api/user 
Content-Type: application/json

{
    "username":"zhangsan",
    "password":"123456",
    "email":"123332211@qq.com",
    "phone":"19234583456",
    "gender":0
}

### 获取
GET http://localhost:7001/api/user
### 修改

PATCH http://localhost:7001/api/user/799a0c2a-953e-4f72-9001-d3925de39502
Content-Type: application/json

{
    "username":"zhangsan4",
    "password":"123456",
    "email":"123332211@qq.com",
    "phone":"19234583456",
    "gender":0

}

### 删除
DELETE http://localhost:7001/api/user/


### 注册
POST http://localhost:7001/signup
Content-Type: application/json

{
    "username":"suqi",
    "password":"123456",
    "email":"123332211@qq.com",
    "phone":"19234583456",
    "gender":0
}

###
POST http://localhost:7001/signin
Content-Type: application/json

{
    "username":"lisi",
    "password":"123456"
}

###
GET http://localhost:7001/api/role/getUser
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ6aGFuZ3NoYW4iLCJwaG9uZSI6IjE5MjM0NTgzNDU2IiwiZW1haWwiOiIxMjMzMzIyMTFAcXEuY29tIiwiZ2VuZGVyIjowLCJpYXQiOjE2MTQ2NzYwMTh9.CmLqpuc3LXPGdIE6_rhVuF1fKp3cSLuhFLZniGBDDU4